apps/game/urls.py
from django.urls import path
from . import views

app_name = "game"

urlpatterns = [
    path("", views.board_view, name="game_page"),
    path("click/", views.on_click, name="click"),
    path("reset/", views.reset_board, name="reset"),
    path("flip/", views.flip_board, name="flip"),
]

hexchess/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.game.urls")),
    path("game/", include("apps.game.urls")),
]

apps/game/models.py
from django.db import models

# Create your models here.

apps/game/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader

from engine.board import Board

# Create your views here.

board = Board()


def board_view(request):
    flipped = request.session.get("flipped", False)
    template = loader.get_template("game/board.html")
    context = {
        "board": board.as_json(flipped),
        "turn": "White" if board.turn == 0 else "Black",
    }
    return HttpResponse(template.render(context, request))


def on_click(request):
    if request.method == "POST":
        tile_id = request.POST.get("tile_id").split()
        if board.on_click(int(tile_id[0]), int(tile_id[1])):
            return HttpResponseRedirect(reverse("game:flip"))
        else:
            return HttpResponseRedirect(reverse("game:game_page"))


def reset_board(request):
    if request.method == "POST":
        board.__init__()
        request.session["flipped"] = False
        return HttpResponseRedirect(reverse("game:game_page"))


def flip_board(request):
    flipped = request.session.get("flipped", False)
    request.session["flipped"] = not flipped
    return HttpResponseRedirect(reverse("game:game_page"))

apps/game/templates/game/board.html
{% load static %}

<link rel="stylesheet" href="{% static 'game/style.css' %}">


<form id="click_form" method="POST" action="{% url 'game:click' %}" style="display:none;">
    {% csrf_token %}
    <input type="hidden" name="tile_id" id="tile_input">
</form>

<form id="reset_form" method="POST" action="{% url 'game:reset' %}">
    {% csrf_token %}
    <input type="submit" value="Reset Board">
</form>

<form id="flip_form" method="POST" action="{% url 'game:flip' %}">
    {% csrf_token %}
    <input type="submit" value="Flip Board">
</form>

<p> {{turn}} to move </p>

<svg id="board" width="100vw" height="100vh" viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg" style="display:block; background:#f0f0f0;">
    {% for tile in board %}
        <polygon
            points="{{tile.points}}"
            style="fill:{{tile.color}};stroke:black;stroke-width:2" 
            id="{{ tile.q }} {{ tile.r }}"
            onclick="submit_click(this)"
        />
        {% if tile.selected %}
            <polygon
                points="{{tile.points}}"
                style="fill:black;fill-opacity:0.4;stroke:black;stroke-width:2"
                styke="pointer-events: none;"
            />
        {% endif %} 
        {% if tile.piece %}
            {% with 'game/assets/'|add:tile.piece_path as image_path%}
                <image href="{% static image_path %}" x="{{ tile.piece_x }}" y="{{ tile.piece_y }}" width="30" style="pointer-events: none;"/>
            {% endwith %}
        {% endif %}
        {% if tile.highlighted %}
            <circle cx="{{tile.center_x}}" cy="{{tile.center_y}}" r="10" fill="black" fill-opacity="0.5" style="pointer-events: none;"/>
        {% endif %}

    {% endfor %}
</svg>



{% comment %} 
TODO 
- add some kind of check notification
{% endcomment %}

<script>
    function submit_click(element) {
      const tile_id = element.getAttribute("id");
      const input = document.getElementById("tile_input");
      input.value = tile_id;
  
      document.getElementById("click_form").submit();
    }
</script>